# Generated by Django 4.2.7 on 2023-11-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbInterface", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
