# Generated by Django 4.2.7 on 2023-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbInterface", "0005_remove_cart_products_cartitem_cart_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
